### ISSUE TITLE
Fallout 4 nifs?

### ISSUE THREAD

**Issue by AncientKhan** [niftools/blender_niftools_addon#498] opened 2022-01-07 09:31 UTC
Can these work or no? I can only see fo3 as a readable game but could fo4 nifs pass as fo3's? I also got a string of errors about python when I tried importing a fo4 nif.

**Comment by neomonkeus** [comment] 2022-01-07 09:33
Duplicate of discussion item - https://github.com/niftools/blender_niftools_addon/discussions/473

**Closed by neomonkeus** 2022-01-07 09:33 UTC
