### ISSUE TITLE
Read/Import Fail: Problem in NIF 2.6

### ISSUE THREAD

**Issue by juliolitwin** [niftools/blender_niftools_addon#450] opened 2021-08-09 17:04 UTC
# Issue Overview
Problem importing NIF's and KF's.

The h_m.nif file is the skeleton example for testing, unfortunately the plugin is not able to read correctly, especially when creating the armature. 

And it even creates cubes in skeleton. Apparently NifSkope can read the file without problem, but the texture reading is incorrect. And it is also not possible to read the animations. 

### Blender Niftools Addon Version Info
v0.0.6

### Blender Version Info
2.93.1 (tested in others blender)

### Platform information
Windows 10

## Context
The NIF version is 2.6, I believe it is not fully supported or there is a specific case not being handled with niftools. So there is the problem of reading the file. Probably the error of the .kf file is just because of the failure of reading the NIF, therefore it gives an error to import.

There is a certain relevance for me, I would like to export as much of the game files as possible to FBX. I want to start a personal project at Unity, but unfortunately my biggest problem is only Gamebryo that disturbs me, with its high level of implementation, it's not easy to do the reverse part of Gamebryo. And also with the possible fix, can help other people and create more support for Niftools. 

## Steps to Reproduce

1. Open the Blender.
2. Go to File/Import/NetImmerse/Gamebryo (.nif) or File/Import/NetImmerse/Gamebryo (.kf)
3. Go to the folder where the nifs files are located.
4. Select the h_m.nif and import.
5. Import any .kf file too.

## Expected Result
Correctly import files into Blender, import meshes, animations, etc. 

## Actual Result
The armature is not imported and there are cubes generated. 

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
[Click to view the screenshot](https://prnt.sc/1ls45ij)

[.kf import error](https://prnt.sc/1ls9qmi)

### Info Bar Output
Just show "Finished".

### Console Output

<details>
  <summary>Complete log</summary>

> Read prefs: C:\Users\Julio Litwin\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
> {'INFO'}: Loading: Blender Niftools Addon: v0.0.6
> {'INFO'}: Loading: PyFFi: 2.2.4.dev3
> {'DEBUG'}: Starting registration
> {'DEBUG'}: Configuring auto-updater
> io_scene_niftools updater verbose is enabled
> io_scene_niftools Updater: Read in JSON settings from file
> {'DEBUG'}: Registering submodules for: io_scene_niftools
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.update
> {'DEBUG'}: Registered Classes: ['UpdaterPreferences']
> {'DEBUG'}: Registering submodules for: io_scene_niftools.properties
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.armature
> {'DEBUG'}: Registered Classes: ['BoneProperty', 'ArmatureProperty']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.collision
> {'DEBUG'}: Registered Classes: ['CollisionProperty']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.constraint
> {'DEBUG'}: Registered Classes: ['ConstraintProperty']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.geometry
> {'DEBUG'}: Registered Classes: ['SkinPartHeader', 'SkinPartFlags']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.material
> {'DEBUG'}: Registered Classes: ['Material', 'AlphaFlags']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.object
> {'DEBUG'}: Registered Classes: ['ExtraData', 'ExtraDataStore', 'ObjectProperty', 'BsInventoryMarker']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.shader
> {'DEBUG'}: Registered Classes: ['ShaderProps']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.scene
> {'DEBUG'}: Registered Classes: ['Scene']
> {'DEBUG'}: Registered the following submodules: ['io_scene_niftools.properties.armature', 'io_scene_niftools.properties.collision', 'io_scene_niftools.properties.constraint', 'io_scene_niftools.properties.geometry', 'io_scene_niftools.properties.material', 'io_scene_niftools.properties.object', 'io_scene_niftools.properties.shader', 'io_scene_niftools.properties.scene']
> {'DEBUG'}: Registering submodules for: io_scene_niftools.operators
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.object
> {'DEBUG'}: Registered Classes: ['BSXExtraDataAdd', 'UPBExtraDataAdd', 'SampleExtraDataAdd', 'NiExtraDataRemove']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.geometry
> {'DEBUG'}: Registered Classes: ['BsInvMarkerAdd', 'BsInvMarkerRemove', 'NfTlPartFlagAdd', 'NfTlPartFlagRemove']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_import_op
> {'DEBUG'}: Registered Classes: ['NifImportOperator']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_export_op
> {'DEBUG'}: Registered Classes: ['NifExportOperator']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_import_op
> {'DEBUG'}: Registered Classes: ['KfImportOperator']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_export_op
> {'DEBUG'}: Registered Classes: ['KfExportOperator']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.egm_import_op
> {'DEBUG'}: Registered Classes: ['EgmImportOperator']
> {'DEBUG'}: Registered the following submodules: ['io_scene_niftools.operators.object', 'io_scene_niftools.operators.geometry', 'io_scene_niftools.operators.nif_import_op', 'io_scene_niftools.operators.nif_export_op', 'io_scene_niftools.operators.kf_import_op', 'io_scene_niftools.operators.kf_export_op', 'io_scene_niftools.operators.egm_import_op']
> {'DEBUG'}: Registering submodules for: io_scene_niftools.ui
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.armature
> {'DEBUG'}: Registered Classes: ['BonePanel', 'ArmaturePanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.collision
> {'DEBUG'}: Registered Classes: ['CollisionBoundsPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.geometry
> {'DEBUG'}: Registered Classes: ['PartFlagPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.material
> {'DEBUG'}: Registered Classes: ['MaterialColorPanel', 'MaterialFlagPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.object
> {'DEBUG'}: Registered Classes: ['ObjectBSInvMarkerPanel', 'ObjectExtraDataList', 'ObjectExtraDataType', 'ObjectExtraData', 'ObjectPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators
> {'DEBUG'}: Registered Classes: ['OperatorCommonDevPanel']
> {'DEBUG'}: Registering submodules for: io_scene_niftools.ui.operators
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_import
> {'DEBUG'}: Registered Classes: ['OperatorImportIncludePanel', 'OperatorImportTransformPanel', 'OperatorImportGeometryPanel', 'OperatorImportArmaturePanel', 'OperatorImportAnimationPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_export
> {'DEBUG'}: Registered Classes: ['OperatorExportTransformPanel', 'OperatorExportArmaturePanel', 'OperatorExportAnimationPanel', 'OperatorExportOptimisePanel']
> {'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.operators.nif_import', 'io_scene_niftools.ui.operators.nif_export']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.shader
> {'DEBUG'}: Registered Classes: ['ShaderPanel']
> {'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.scene
> {'DEBUG'}: Registered Classes: ['ScenePanel', 'SceneVersionInfoPanel']
> {'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.armature', 'io_scene_niftools.ui.collision', 'io_scene_niftools.ui.geometry', 'io_scene_niftools.ui.material', 'io_scene_niftools.ui.object', 'io_scene_niftools.ui.operators', 'io_scene_niftools.ui.shader', 'io_scene_niftools.ui.scene']
> {'DEBUG'}: Registered the following submodules: ['io_scene_niftools.update', 'io_scene_niftools.properties', 'io_scene_niftools.operators', 'io_scene_niftools.ui']
> niftools:INFO:Dev: Sys variable not set
> niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.6(running on Blender 2.93.1, PyFFI 2.2.4.dev3)
> niftools:INFO:Importing C:\Projects\Arcana\bin\client\data\character\h_m.nif
> niftools:INFO:NIF file version: 14060000
> niftools:INFO:Reading file
> niftools:INFO:Importing data
> niftools:INFO:Scale Correction set to 0.10000000149011612
> pyffi.toaster:INFO:--- fix_scale ---
> pyffi.toaster:INFO:  scaling by factor 0.100000
> pyffi.toaster:INFO:  ~~~ NiNode [Scene Root] ~~~
> pyffi.toaster:INFO:    ~~~ NiVertexColorProperty [] ~~~
> pyffi.toaster:INFO:    ~~~ NiZBufferProperty [] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [foot_dummy] ~~~
> pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:      ~~~ NiNode [Bip01] ~~~
> pyffi.toaster:INFO:        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:        ~~~ NiTransformController [] ~~~
> pyffi.toaster:INFO:        ~~~ NiNode [Bip01 NonAccum] ~~~
> pyffi.toaster:INFO:          ~~~ NiNode [Bip01 Footsteps] ~~~
> pyffi.toaster:INFO:          ~~~ NiNode [Bip01 Pelvis] ~~~
> pyffi.toaster:INFO:            ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bip01 Spine] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bip01 Spine1] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bip01 Spine2] ~~~
> pyffi.toaster:INFO:                  ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                  ~~~ NiNode [Bip01 Neck] ~~~
> pyffi.toaster:INFO:                    ~~~ NiNode [Bip01 Head] ~~~
> pyffi.toaster:INFO:                      ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bip01 Ponytail1] ~~~
> pyffi.toaster:INFO:                        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bip01 Ponytail11] ~~~
> pyffi.toaster:INFO:                          ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                          ~~~ NiNode [Bip01 Ponytail12] ~~~
> pyffi.toaster:INFO:                            ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bip01 Ponytail2] ~~~
> pyffi.toaster:INFO:                        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bip01 Ponytail21] ~~~
> pyffi.toaster:INFO:                          ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                          ~~~ NiNode [Bip01 Ponytail22] ~~~
> pyffi.toaster:INFO:                            ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bone03] ~~~
> pyffi.toaster:INFO:                        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bone04] ~~~
> pyffi.toaster:INFO:                          ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bone01] ~~~
> pyffi.toaster:INFO:                        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bone02] ~~~
> pyffi.toaster:INFO:                          ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [head_dummy] ~~~
> pyffi.toaster:INFO:                        ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                    ~~~ NiNode [Bip01 L Clavicle] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bip01 L UpperArm] ~~~
> pyffi.toaster:INFO:                        ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bip01 L Forearm] ~~~
> pyffi.toaster:INFO:                          ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                          ~~~ NiNode [Bip01 L Hand] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Bip01 L Finger0] ~~~
> pyffi.toaster:INFO:                              ~~~ NiNode [Bip01 L Finger01] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Bip01 L Finger1] ~~~
> pyffi.toaster:INFO:                              ~~~ NiNode [Bip01 L Finger11] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Lhand_dummy] ~~~
> pyffi.toaster:INFO:                              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                          ~~~ NiNode [Larm_dummy] ~~~
> pyffi.toaster:INFO:                            ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                    ~~~ NiNode [Bip01 R Clavicle] ~~~
> pyffi.toaster:INFO:                      ~~~ NiNode [Bip01 R UpperArm] ~~~
> pyffi.toaster:INFO:                        ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                        ~~~ NiNode [Bip01 R Forearm] ~~~
> pyffi.toaster:INFO:                          ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                          ~~~ NiNode [Bip01 R Hand] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Bip01 R Finger0] ~~~
> pyffi.toaster:INFO:                              ~~~ NiNode [Bip01 R Finger01] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Bip01 R Finger1] ~~~
> pyffi.toaster:INFO:                              ~~~ NiNode [Bip01 R Finger11] ~~~
> pyffi.toaster:INFO:                            ~~~ NiNode [Rhand_dummy] ~~~
> pyffi.toaster:INFO:                              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                  ~~~ NiNode [body_dummy] ~~~
> pyffi.toaster:INFO:                    ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bip01 L Thigh] ~~~
> pyffi.toaster:INFO:                ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bip01 L Calf] ~~~
> pyffi.toaster:INFO:                  ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                  ~~~ NiNode [Bip01 L Foot] ~~~
> pyffi.toaster:INFO:                    ~~~ NiNode [Bip01 L Toe0] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bip01 R Thigh] ~~~
> pyffi.toaster:INFO:                ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bip01 R Calf] ~~~
> pyffi.toaster:INFO:                  ~~~ NiCollisionData [] ~~~
> pyffi.toaster:INFO:                  ~~~ NiNode [Bip01 R Foot] ~~~
> pyffi.toaster:INFO:                    ~~~ NiNode [Bip01 R Toe0] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bone15] ~~~
> pyffi.toaster:INFO:              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone16] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bone17] ~~~
> pyffi.toaster:INFO:                  ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bone12] ~~~
> pyffi.toaster:INFO:              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone13] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bone14] ~~~
> pyffi.toaster:INFO:                  ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bone07] ~~~
> pyffi.toaster:INFO:              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone08] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bone09] ~~~
> pyffi.toaster:INFO:                  ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone24] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:                ~~~ NiNode [Bone25] ~~~
> pyffi.toaster:INFO:                  ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bone05] ~~~
> pyffi.toaster:INFO:              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone06] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:            ~~~ NiNode [Bone22] ~~~
> pyffi.toaster:INFO:              ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:              ~~~ NiNode [Bone23] ~~~
> pyffi.toaster:INFO:                ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [face] ~~~
> pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [face] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct01] ~~~
> pyffi.toaster:INFO:      ~~~ NiDirectionalLight [] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct01.Target] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct02] ~~~
> pyffi.toaster:INFO:      ~~~ NiDirectionalLight [] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct02.Target] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct04.Target] ~~~
> pyffi.toaster:INFO:    ~~~ NiNode [Direct04] ~~~
> pyffi.toaster:INFO:      ~~~ NiDirectionalLight [] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [hand] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageQuality] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [UseMasterIndexForAll] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FileSettings] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MaxAnisotropy] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [AutoGenMipMaps] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterModeEx] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageSize] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegerExtraData [MasterIndex] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MipMapMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [hand] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [body2] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageQuality] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [UseMasterIndexForAll] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FileSettings] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MaxAnisotropy] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [AutoGenMipMaps] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterModeEx] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageSize] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegerExtraData [MasterIndex] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MipMapMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [body2] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [body1] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageQuality] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [UseMasterIndexForAll] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FileSettings] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MaxAnisotropy] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [AutoGenMipMaps] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterModeEx] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageSize] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegerExtraData [MasterIndex] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MipMapMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [body1] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [foot] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageQuality] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [UseMasterIndexForAll] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FileSettings] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MaxAnisotropy] ~~~
> pyffi.toaster:INFO:      ~~~ NiBooleanExtraData [AutoGenMipMaps] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterModeEx] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FinalImageSize] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegerExtraData [MasterIndex] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [FilterMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiIntegersExtraData [MipMapMode] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [foot] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiMesh [hair] ~~~
> pyffi.toaster:INFO:      ~~~ NiStencilProperty [] ~~~
> pyffi.toaster:INFO:      ~~~ NiMaterialProperty [hair] ~~~
> pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
> pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiDataStream [] ~~~
> pyffi.toaster:INFO:      ~~~ NiSkinningMeshModifier [] ~~~
> pyffi.toaster:INFO:    ~~~ NiAmbientLight [] ~~~
> niftools:INFO:Importing data for block 'Scene Root'
> niftools:INFO:Importing data for block 'foot_dummy'
> niftools:INFO:Importing data for block 'Bip01'
> niftools:INFO:Importing data for block 'Bip01 NonAccum'
> niftools:INFO:Importing data for block 'Bip01 Footsteps'
> niftools:INFO:Importing data for block 'Bip01 Pelvis'
> niftools:INFO:Importing data for block 'Bip01 Spine'
> niftools:INFO:Importing data for block 'Bip01 Spine1'
> niftools:INFO:Importing data for block 'Bip01 Spine2'
> niftools:INFO:Importing data for block 'Bip01 Neck'
> niftools:INFO:Importing data for block 'Bip01 Head'
> niftools:INFO:Importing data for block 'Bip01 Ponytail1'
> niftools:INFO:Importing data for block 'Bip01 Ponytail11'
> niftools:INFO:Importing data for block 'Bip01 Ponytail12'
> niftools:INFO:Importing data for block 'Bip01 Ponytail2'
> niftools:INFO:Importing data for block 'Bip01 Ponytail21'
> niftools:INFO:Importing data for block 'Bip01 Ponytail22'
> niftools:INFO:Importing data for block 'Bone03'
> niftools:INFO:Importing data for block 'Bone04'
> niftools:INFO:Importing data for block 'Bone01'
> niftools:INFO:Importing data for block 'Bone02'
> niftools:INFO:Importing data for block 'head_dummy'
> niftools:INFO:Importing data for block 'Bip01 L Clavicle'
> niftools:INFO:Importing data for block 'Bip01 L UpperArm'
> niftools:INFO:Importing data for block 'Bip01 L Forearm'
> niftools:INFO:Importing data for block 'Bip01 L Hand'
> niftools:INFO:Importing data for block 'Bip01 L Finger0'
> niftools:INFO:Importing data for block 'Bip01 L Finger01'
> niftools:INFO:Importing data for block 'Bip01 L Finger1'
> niftools:INFO:Importing data for block 'Bip01 L Finger11'
> niftools:INFO:Importing data for block 'Lhand_dummy'
> niftools:INFO:Importing data for block 'Larm_dummy'
> niftools:INFO:Importing data for block 'Bip01 R Clavicle'
> niftools:INFO:Importing data for block 'Bip01 R UpperArm'
> niftools:INFO:Importing data for block 'Bip01 R Forearm'
> niftools:INFO:Importing data for block 'Bip01 R Hand'
> niftools:INFO:Importing data for block 'Bip01 R Finger0'
> niftools:INFO:Importing data for block 'Bip01 R Finger01'
> niftools:INFO:Importing data for block 'Bip01 R Finger1'
> niftools:INFO:Importing data for block 'Bip01 R Finger11'
> niftools:INFO:Importing data for block 'Rhand_dummy'
> niftools:INFO:Importing data for block 'body_dummy'
> niftools:INFO:Importing data for block 'Bip01 L Thigh'
> niftools:INFO:Importing data for block 'Bip01 L Calf'
> niftools:INFO:Importing data for block 'Bip01 L Foot'
> niftools:INFO:Importing data for block 'Bip01 L Toe0'
> niftools:INFO:Importing data for block 'Bip01 R Thigh'
> niftools:INFO:Importing data for block 'Bip01 R Calf'
> niftools:INFO:Importing data for block 'Bip01 R Foot'
> niftools:INFO:Importing data for block 'Bip01 R Toe0'
> niftools:INFO:Importing data for block 'Bone15'
> niftools:INFO:Importing data for block 'Bone16'
> niftools:INFO:Importing data for block 'Bone17'
> niftools:INFO:Importing data for block 'Bone12'
> niftools:INFO:Importing data for block 'Bone13'
> niftools:INFO:Importing data for block 'Bone14'
> niftools:INFO:Importing data for block 'Bone07'
> niftools:INFO:Importing data for block 'Bone08'
> niftools:INFO:Importing data for block 'Bone09'
> niftools:INFO:Importing data for block 'Bone24'
> niftools:INFO:Importing data for block 'Bone25'
> niftools:INFO:Importing data for block 'Bone05'
> niftools:INFO:Importing data for block 'Bone06'
> niftools:INFO:Importing data for block 'Bone22'
> niftools:INFO:Importing data for block 'Bone23'
> niftools:INFO:Importing data for block 'face'
> niftools:INFO:Importing data for block 'Direct01'
> niftools:INFO:Importing data for block ''
> niftools:INFO:Importing data for block 'Direct01.Target'
> niftools:INFO:Importing data for block 'Direct02'
> niftools:INFO:Importing data for block ''
> niftools:INFO:Importing data for block 'Direct02.Target'
> niftools:INFO:Importing data for block 'Direct04.Target'
> niftools:INFO:Importing data for block 'Direct04'
> niftools:INFO:Importing data for block ''
> niftools:INFO:Importing data for block 'hand'
> niftools:INFO:Importing data for block 'body2'
> niftools:INFO:Importing data for block 'body1'
> niftools:INFO:Importing data for block 'foot'
> niftools:INFO:Importing data for block 'hair'
> niftools:INFO:Importing data for block ''
> niftools:INFO:Finished

<details>

### Nif File
[Download nif's examples](https://drive.google.com/file/d/1rhAS4_1ubM1_Vodzf9LjtcaOECJIPtRq/view?usp=sharing)

## Additional Information
Thank you for this excellent project!

**Comment by juliolitwin** [comment] 2021-09-25 15:59
Is there any idea of the issue's problem?

**Comment by neomonkeus** [comment] 2021-11-22 13:32
@juliolitwin can you retry with the latest version of the add-on to see if the issue is still there as there has been great work done in the area of armature in the past two releases.

**Comment by juliolitwin** [comment] 2021-11-22 16:45
Hey @neomonkeus, thanks for replying.

I was following the @HENDRIX-ZT2 commits and already made the test with the latest release (version 0.0.12), but unfortunately all the aforementioned bugs still persist.

**Comment by neomonkeus** [comment] 2021-11-22 16:48
Thanks for verifying.

**Comment by HENDRIX-ZT2** [comment] 2021-11-22 17:06
Yeah, because of my fixes this has become a duplicate of #480. The root controller NiSequenceData has not been decoded in the old pyffi version we rely upon. We can only address #480 once we migrate to the new codegen and nif current XML version.

Closed as duplicate of #480.

**Closed by HENDRIX-ZT2** 2021-11-22 17:06 UTC
Labels: Bug
