### ISSUE TITLE
Can't open Nif File

### ISSUE THREAD

**Issue by User-Error-404** [niftools/blender_niftools_addon#611] opened 2023-10-04 19:40 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X ] Read the user documentation.
 - [ X] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

### Blender Niftools Addon Version Info
**blender_niftools_addon-v0.1.0-2023-06-20-43341a10**

### Blender Version Info
**Blender 3.6**

### Platform information
**Windows 10**

## Context
**When opening a Nif file for Fallout 4 I have I get the following error: **

Python: Traceback (most recent call last):
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 207, in import_branch
    b_obj = self.armaturehelper.import_armature(n_block)
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 226, in import_armature
    self.store_bind_matrices(n_armature)
  File "C:\Users\0x404\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 173, in store_bind_matrices
    self.bind_store[bonenode] = self.get_skin_bind(bonedata.get_transform(), geom, n_armature)
AttributeError: 'BSSkinBoneTrans' object has no attribute 'get_transform'

**Comment by Candoran2** [comment] 2023-10-04 20:31
Could you attach the nif file (preferably as a zip drag-and-dropped into the issue)?

**Comment by User-Error-404** [comment] 2023-10-04 20:35
> Member

[Police.zip](https://github.com/niftools/blender_niftools_addon/files/12807950/Police.zip)

**Comment by Candoran2** [comment] 2023-10-04 20:39
Duplicate of 598

**Comment by Candoran2** [comment] 2023-10-04 20:40
Duplicate of #598

**Comment by Candoran2** [comment] 2023-10-04 20:41
Since this appears to be a duplicate, you can follow the linked issue instead for the progress.

**Closed by Candoran2** 2023-10-04 20:40 UTC
Labels: Bug

**Comment by User-Error-404** [comment] 2023-10-04 20:48
> Since this appears to be a duplicate, you can follow the linked issue instead for the progress.

Where is the issue ? I clicked on #598 but it's the same problem as my

**Comment by Candoran2** [comment] 2023-10-04 20:57
> Where is the issue ? I clicked on #598 but it's the same problem as my

Yes, that's what a duplicate means. Because this issue is already reported there, there is no reason to keep this issue open, since everything relevant is already tracked in the other issue.
