### ISSUE TITLE
In the file BhkWeldInfo.py 'false' is written with a lowercase letter

### ISSUE THREAD

**Issue by agronack** [niftools/blender_niftools_addon#588] opened 2023-07-10 16:57 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**In the file BhkWeldInfo.py 'false' is written with a lowercase letter. That should be fixed**

### Blender Niftools Addon Version Info
**0.1.0**

## Screenshot
![scn](https://github.com/niftools/blender_niftools_addon/assets/118005852/d2e194bb-fed9-4096-ba7d-9a898b98910c)

**Comment by Candoran2** [comment] 2023-07-11 12:33
This is a duplicate of #580 . It should be fixed in the next release, since reddraconi made OpenNaja/cobra-tools#336

**Closed** 2023-07-11 12:34 UTC
Labels: Bug
