### ISSUE TITLE
Error when exporting a nif file for the Oblivion game (when creating a collision for a static object)

### ISSUE THREAD

**Issue by Ggleebb** [niftools/blender_niftools_addon#564] opened 2023-03-12 21:55 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
After I created a collision for my model and tried to export to Oblivion, an error came out. I decided to take a 3d model of the table from oblivion. I imported it into a Blender and tried to export it. Exactly the same mistake.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
v0.0.14

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
3.3.1

### Platform information
**[Provide a brief overview of what OS your running on]**
Windows 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
Error when exporting a nif file for the Oblivion game (when creating a collision for a static object). The error is issued even if I try to export a 3d model from the game. I.e., for the sake of experiment, I pulled the model out of the game, imported it into a blender, and then tried to export, but an error came out. The same error pops up when I create a collision according to the documentation, and then try to export. And this problem is only with static objects. For example, the sword is exported without problems. P.S. sorry for my English :)

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 1) Import, for example, a table model from oblivion into a Blender.
2) Export the table model (including collisions) in Nif format.
3) Error when exporting (all the same if you created a collision for your model and tried to export).

## Expected Result
**[Describe what you expected to have resulted from this process]**
3D Model in Nif format

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
It is not possible to export with a collision. The model is exported without collision.

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**
This is the first time I'm writing a comment here and I haven't figured out how to leave screenshots yet. So I'll leave a link ^_^:
[Imported model](https://ibb.co/BKXSp2N)
[Error](https://ibb.co/kxtLJKJ)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**
[Link to the oblivion table file in nif format](https://drive.google.com/file/d/1UTrR4joQOK-Tzjax-OQrAhytoCh1VwPE/view?usp=share_link)

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

> Traceback (most recent call last):
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_export.py", line 136, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 106, in export_root_node
    self.export_node(b_obj, None)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 234, in export_children
    self.export_node(b_child, temp_parent)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 167, in export_node
    if self.export_collision(b_obj, n_parent):
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 255, in export_collision
    self.bhk_helper.export_collision_helper(b_obj, node)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 127, in export_collision_helper
    self.export_collision_packed(b_obj, n_col_body, layer, n_havok_mat)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 525, in export_collision_packed
    vertices = [vert.co * transform for vert in b_mesh.vertices]
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 525, in <listcomp>
    vertices = [vert.co * transform for vert in b_mesh.vertices]
TypeError: Element-wise multiplication: not supported between 'Vector' and 'Matrix' types

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

> Read prefs: C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
{'INFO'}: Loading: Blender Niftools Addon: v0.0.14
{'INFO'}: Loading: PyFFi: 2.2.4.dev3
{'DEBUG'}: Starting registration
{'DEBUG'}: Configuring auto-updater
io_scene_niftools updater verbose is enabled
io_scene_niftools Updater: Read in JSON settings from file
{'DEBUG'}: Registering submodules for: io_scene_niftools
{'DEBUG'}: Registering Classes for module: io_scene_niftools.update
{'DEBUG'}: Registered Classes: ['UpdaterPreferences']
{'DEBUG'}: Registering submodules for: io_scene_niftools.properties
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.armature
{'DEBUG'}: Registered Classes: ['BoneProperty', 'ArmatureProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.collision
{'DEBUG'}: Registered Classes: ['CollisionProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.constraint
{'DEBUG'}: Registered Classes: ['ConstraintProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.material
{'DEBUG'}: Registered Classes: ['Material', 'AlphaFlags']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.object
{'DEBUG'}: Registered Classes: ['ExtraData', 'ExtraDataStore', 'ObjectProperty', 'BsInventoryMarker']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.shader
{'DEBUG'}: Registered Classes: ['ShaderProps']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.scene
{'DEBUG'}: Registered Classes: ['Scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.properties.armature', 'io_scene_niftools.properties.collision', 'io_scene_niftools.properties.constraint', 'io_scene_niftools.properties.material', 'io_scene_niftools.properties.object', 'io_scene_niftools.properties.shader', 'io_scene_niftools.properties.scene']
{'DEBUG'}: Registering submodules for: io_scene_niftools.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.object
{'DEBUG'}: Registered Classes: ['BSXExtraDataAdd', 'UPBExtraDataAdd', 'SampleExtraDataAdd', 'NiExtraDataRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.geometry
{'DEBUG'}: Registered Classes: ['BsInvMarkerAdd', 'BsInvMarkerRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_import_op
{'DEBUG'}: Registered Classes: ['NifImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_export_op
{'DEBUG'}: Registered Classes: ['NifExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_import_op
{'DEBUG'}: Registered Classes: ['KfImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_export_op
{'DEBUG'}: Registered Classes: ['KfExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.egm_import_op
{'DEBUG'}: Registered Classes: ['EgmImportOperator']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.operators.object', 'io_scene_niftools.operators.geometry', 'io_scene_niftools.operators.nif_import_op', 'io_scene_niftools.operators.nif_export_op', 'io_scene_niftools.operators.kf_import_op', 'io_scene_niftools.operators.kf_export_op', 'io_scene_niftools.operators.egm_import_op']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.armature
{'DEBUG'}: Registered Classes: ['BonePanel', 'ArmaturePanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.collision
{'DEBUG'}: Registered Classes: ['CollisionBoundsPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.material
{'DEBUG'}: Registered Classes: ['MaterialColorPanel', 'MaterialFlagPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.object
{'DEBUG'}: Registered Classes: ['ObjectBSInvMarkerPanel', 'ObjectExtraDataList', 'ObjectExtraDataType', 'ObjectExtraData', 'ObjectPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators
{'DEBUG'}: Registered Classes: ['OperatorCommonDevPanel']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_import
{'DEBUG'}: Registered Classes: ['OperatorImportIncludePanel', 'OperatorImportTransformPanel', 'OperatorImportGeometryPanel', 'OperatorImportTexturePanel', 'OperatorImportArmaturePanel', 'OperatorImportAnimationPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_export
{'DEBUG'}: Registered Classes: ['OperatorExportTransformPanel', 'OperatorExportArmaturePanel', 'OperatorExportAnimationPanel', 'OperatorExportOptimisePanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.operators.nif_import', 'io_scene_niftools.ui.operators.nif_export']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.shader
{'DEBUG'}: Registered Classes: ['ShaderPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.scene
{'DEBUG'}: Registered Classes: ['ScenePanel', 'SceneVersionInfoPanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.armature', 'io_scene_niftools.ui.collision', 'io_scene_niftools.ui.material', 'io_scene_niftools.ui.object', 'io_scene_niftools.ui.operators', 'io_scene_niftools.ui.shader', 'io_scene_niftools.ui.scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.update', 'io_scene_niftools.properties', 'io_scene_niftools.operators', 'io_scene_niftools.ui']
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.14(running on Blender 3.3.1, PyFFI 2.2.4.dev3)
niftools:INFO:Importing C:\Users\glebs\Desktop\uppertable02.nif
niftools:INFO:NIF file version: 14000005
niftools:INFO:Reading file
niftools:INFO:Importing data
niftools:INFO:Scale Correction set to 0.10000000149011612
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 0.100000
pyffi.toaster:INFO:  ~~~ NiNode [upperTable02] ~~~
pyffi.toaster:INFO:    ~~~ BSXFlags [BSX] ~~~
pyffi.toaster:INFO:    ~~~ NiStringExtraData [UPB] ~~~
pyffi.toaster:INFO:    ~~~ bhkCollisionObject [] ~~~
pyffi.toaster:INFO:      ~~~ bhkRigidBodyT [] ~~~
pyffi.toaster:INFO:        ~~~ bhkMoppBvTreeShape [] ~~~
pyffi.toaster:INFO:          ~~~ bhkPackedNiTriStripsShape [] ~~~
pyffi.toaster:INFO:            ~~~ hkPackedNiTriStripsData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTriStrips [upperTable02:0] ~~~
pyffi.toaster:INFO:      ~~~ NiBinaryExtraData [Tangent space (binormal & tangent vectors)] ~~~
pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:      ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:      ~~~ NiMaterialProperty [Material #151] ~~~
pyffi.toaster:INFO:      ~~~ NiTriStripsData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTriStrips [upperTable02:1] ~~~
pyffi.toaster:INFO:      ~~~ NiBinaryExtraData [Tangent space (binormal & tangent vectors)] ~~~
pyffi.toaster:INFO:      ~~~ NiMaterialProperty [Material #153] ~~~
pyffi.toaster:INFO:      ~~~ NiTriStripsData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTriStrips [upperTable02:2] ~~~
pyffi.toaster:INFO:      ~~~ NiBinaryExtraData [Tangent space (binormal & tangent vectors)] ~~~
pyffi.toaster:INFO:      ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:      ~~~ NiMaterialProperty [wood detail] ~~~
pyffi.toaster:INFO:      ~~~ NiTriStripsData [] ~~~
niftools:INFO:Importing data for block 'upperTable02'
niftools:INFO:Importing data for block 'upperTable02:0'
niftools:INFO:Importing mesh data for geometry 'upperTable02:0'
niftools:WARNING:Texture 'intstainewood02.dds' not found or not supported and no alternate available
niftools:INFO:Importing data for block 'upperTable02:1'
niftools:INFO:Importing mesh data for geometry 'upperTable02:1'
niftools:INFO:Importing data for block 'upperTable02:2'
niftools:INFO:Importing mesh data for geometry 'upperTable02:2'
niftools:WARNING:Texture 'Wooddetail01.dds' not found or not supported and no alternate available
niftools:INFO:Finished
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.14(running on Blender 3.3.1, PyFFI 2.2.4.dev3)
niftools:INFO:Exporting C:\Users\glebs\Documents\untitled.nif
niftools:INFO:Exporting
niftools:INFO:Exporting geometry and animation
niftools:INFO:Writing NIF version 0x14000005
niftools:INFO:Exporting <bpy_struct, Object("upperTable02") at 0x00000230DC99C108> as NiNode block
niftools:INFO:Exporting <bpy_struct, Object("poly0") at 0x00000230DBFF2408> as bhkCollisionObject block
niftools:INFO:Exporting <bpy_struct, Object("poly0") at 0x00000230DBFF2408> as bhkRigidBody block
niftools:INFO:Exporting <bpy_struct, Object("poly0") at 0x00000230DBFF2408> as bhkMoppBvTreeShape block
niftools:INFO:Exporting <bpy_struct, Object("poly0") at 0x00000230DBFF2408> as bhkPackedNiTriStripsShape block
Traceback (most recent call last):
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_export.py", line 136, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 106, in export_root_node
    self.export_node(b_obj, None)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 234, in export_children
    self.export_node(b_child, temp_parent)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 167, in export_node
    if self.export_collision(b_obj, n_parent):
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 255, in export_collision
    self.bhk_helper.export_collision_helper(b_obj, node)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 127, in export_collision_helper
    self.export_collision_packed(b_obj, n_col_body, layer, n_havok_mat)
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 525, in export_collision_packed
    vertices = [vert.co * transform for vert in b_mesh.vertices]
  File "C:\Users\glebs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\collision\havok.py", line 525, in <listcomp>
    vertices = [vert.co * transform for vert in b_mesh.vertices]
TypeError: Element-wise multiplication: not supported between 'Vector' and 'Matrix' types

### Blend File
**[Attach the blend file if the issue is reproducible]**
N/A

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
N/A

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**
https://github.com/niftools/blender_niftools_addon/issues/538

## Additional Information
**[Anything else you feel is relevant]**
No

**Comment by Candoran2** [comment] 2023-03-13 05:44
This reads very much like a duplicate of #453 . Is there any difference between what you have and what is documented there?

**Comment by Ggleebb** [comment] 2023-03-13 09:20
Oh. No. there is no difference. Somehow I didn't find this information. But, having studied this duplicate, I could not fix my problem, unfortunately. :(
With a collision, it is not possible to export. The error started to occur when Bounds was set in the Viewport Display.If you remove Bounds, the export occurs without errors, but at the same time, when I try to start saving in the game next to the model, the game crashes. But this is all already described in #453.

**Comment by Ggleebb** [comment] 2023-03-13 10:32
> This reads very much like a duplicate of #453 . Is there any difference between what you have and what is documented there?

Oh. No. there is no difference. Somehow I didn't find this information. But, having studied this duplicate, I could not fix my problem, unfortunately. :(
With a collision, it is not possible to export. The error started to occur when Bounds was set in the Viewport Display.If you remove Bounds, the export occurs without errors, but at the same time, when I try to start saving in the game next to the model, the game crashes. But this is all already described in https://github.com/niftools/blender_niftools_addon/issues/453.

**Comment by Candoran2** [comment] 2023-03-13 12:05
Alright, then I will close this issue as a duplicate. For further updates you can follow #453

**Comment by Candoran2** [comment] 2023-03-13 12:06
Duplicate of #453

**Closed by Candoran2** 2023-03-13 12:06 UTC
Labels: Bug
