### ISSUE TITLE
Plead for help

### ISSUE THREAD

**Issue by jupiter38** [niftools/blender_niftools_addon#530] opened 2022-08-06 10:45 UTC
Hello, leaders
I use blender 3.2 and blender niftools addon - v0.0.14, After installation, the following errors occurred in importing and exporting NIF files. Please see the attachment. What's the problem?
![error](https://user-images.githubusercontent.com/110722459/183245636-10bcd514-48fb-4a8b-a2a3-90a93e3d1e58.jpg)
?

**Comment by HENDRIX-ZT2** [comment] 2022-08-07 09:52
Duplicate of #327, closed. Read there for further information

**Closed by HENDRIX-ZT2** 2022-08-07 09:52 UTC
