### ISSUE TITLE
Import Failure: Encoding/Decoding

### ISSUE THREAD

**Issue by M4rkFlor** [niftools/blender_niftools_addon#441] opened 2021-04-29 08:30 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [X] Read through the list of `Helpful resources` links on the right-hand side.
 - [X] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [x] Looking for support where the forums, chat or documentation is more appropriate.
 - [x] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Importing a .nif causes UnicodeDecodeError]**

### Blender Niftools Addon Version Info
**[ 0.0.6]**

### Blender Version Info
**[2.92]**

### Platform information
**[Windows 10 Home x64]**

## Context
**[Importing a .nif causes UnicodeDecodeError on n_block.name.decode()]**

## Steps to Reproduce
**[import a .nif]**

## Expected Result
**[Expected model to be imported and loaded into blender render view. ]**

## Actual Result
**[Error is generated and a few bones get loaded into the scene, NifSkope loads the model without issue]**

## Possible Fix
**[The .nif is from a Japanese game that I suspect may or may not contain Japanese characters which may be the reason why n_block.name.decode() is failing, Maybe different .nifs have different encodings]**

## Screenshot
**[just a error log]**

## Logs and Files
**[
[files.zip](https://github.com/niftools/blender_niftools_addon/files/6397183/files.zip)
]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand ?]**

### Console Output
**[in logs and files]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[in logs and files]**

## Similar Known Issues
**[Maybe Similar to #421]**

## Additional Information
**[I decided to bypass the error with ```.decode("shift-jis", errors="surrogateescape")``` and It allows the model to load in, however without texture. Doing this leads to :

AttributeError: module 'io_scene_niftools.modules.nif_import.property.texture' has no attribute 'IMPORT_EMBEDDED_TEXTURES' 

so I bypassed that aswell and got:

AttributeError: 'NiPixelData' object has no attribute 'pixel_data_matrix'

I am starting to think this isn't a small bug and rather possible missing implementation like in issue #421 
here are the extra errors generated 
[extraErrors.txt](https://github.com/niftools/blender_niftools_addon/files/6403252/extraErrors.txt)
]**

**Comment by HENDRIX-ZT2** [comment] 2021-05-01 16:32
![grafik](https://user-images.githubusercontent.com/28632661/116788506-3bd66280-aaaa-11eb-87ea-aeb23409f121.png)
Yup, definitely japanese chars in the file name. So gotta handle the different decode() parameters, perhaps with a try - except clause.

Then the problem is that nipixeldata has not been really looked at for a while. I know there used to be an issue with Pyffi preventing us from reading it. However, IIRC that has been fixed.

Hold on, that hasn't been merged:
https://github.com/niftools/pyffi/pull/68

You're welcome to do a PR for the steps that block it, though.

**Comment by neomonkeus** [comment] 2021-05-03 11:28
> ![grafik](https://user-images.githubusercontent.com/28632661/116788506-3bd66280-aaaa-11eb-87ea-aeb23409f121.png)
> Yup, definitely japanese chars in the file name. So gotta handle the different decode() parameters, perhaps with a try - except clause.
> 
> Then the problem is that nipixeldata has not been really looked at for a while. I know there used to be an issue with Pyffi preventing us from reading it. However, IIRC that has been fixed.
> 
> Hold on, that hasn't been merged:
> [niftools/pyffi#68](https://github.com/niftools/pyffi/pull/68)
> 
> You're welcome to do a PR for the steps that block it, though.

I will take a look at cleaning up the open PRs for Pyffi, but the main issue is that the Pyffi codebase release.

**Closed** 2021-09-26 08:57 UTC
Labels: Bug
