### ISSUE TITLE
Oblivion: Materials are combined on import

### ISSUE THREAD

**Issue by FeuerTiger86** [niftools/blender_niftools_addon#452] opened 2021-08-18 18:03 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Many meshes use the same "NiMaterialProperty" in more than one NiTriShape, each time with different textures. When importing such a mesh, only one Material is created, which is then used for all parts of the mesh that used this NiMaterialProperty. There should be one material per Texture.

I tested this with meshes from Oblivion and Fallout: New Vegas. For Oblivion, the materials were combined, for FNV, this didn't happen. However, NiMaterialProperties don't have names in FNV, but they usually do in Oblivion. Removing the names in Oblivion results in correctly imported materials noname.001, .002, etc. Also, **adding** names to them in FNV results in materials merging on import. Just splitting properties in NifSkope without giving them unique names does not work.

### Blender Niftools Addon Version Info
0.0.6

### Blender Version Info
2.93.2

### Platform information
Windows 10 Professional 64Bit

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
Import Oblivion mesh with shared NiMaterialProperties or more than one with identical names. After importing is finished, there is only one material with that name, using one of the textures in all parts of the model where this NiMaterialProperty was used. 

## Expected Result
There should be as many different materials as textures are used, with .001, .002, etc. as suffix. If the NiMaterialProperty has no name, the correct amount of materials and textures is imported.

## Actual Result
There is only a single material with this name after import, no matter how many different NiTriShapes it was used in, with different textures.
Until I discovered that you could just delete the NiMaterialProperty's name I had to split properties in NifSkope and give each one a unique name to circumvent this.

## Possible Fix
Check for different textures and create duplicate materials.

## Screenshot
![nifImportMaterial](https://user-images.githubusercontent.com/41874291/129949192-69020b6d-18ef-4fed-b483-ad70b812426d.jpg)

**Comment by Candoran2** [comment] 2021-08-31 16:05
> We have to think about how we handle names in this case. Just suffix the material name with .001? And store the original in the long name field?

Materials don't have the long name field (as far as I know), though obviously that could be added. Testing with a Skyrim mesh showed that materials with the same name were merged on import, even if they didn't have the same settings (or were even the same block type), which obviously is not desired behaviour. So aside from just name handling, there needs to be some improvement in how we detect whether materials are the same.

I think suffixing the material name with .001 and so on should be fine. Storing the original name might not be necessary - we could detect whether materials have the same names after removal of that suffix, and could be merged (same settings after export, or even optimisation after already creating the blocks). It could be controlled by the 'optimise materials' export setting (which is currently unused).

**Comment by HENDRIX-ZT2** [comment] 2021-11-22 17:10
Isn't this a dupe of #374?

**Comment by neomonkeus** [comment] 2021-11-22 17:24
Closing as dupe, or at least ensuring that the linked ticket will cover these issues.

**Closed by neomonkeus** 2021-11-22 17:24 UTC
Labels: Improvement, Bug
