### ISSUE TITLE
Can't open Nif file

### ISSUE THREAD

**Issue by Menchi1** [niftools/blender_niftools_addon#436] opened 2021-04-06 09:40 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [O] Read the user documentation.
 - [O] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [O] Looking for support where the forums, chat or documentation is more appropriate.
 - [O] Goes off topic, loses focus or turns into a discussion.
 - [O] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Cant open Nif File
Cant Import and Export

**[Provide a general introduction to the issue and why it is relevant to this repository]**

### Blender Niftools Addon Version Info
0.0.5

### Blender Version Info
2.9

### Platform information
Win10

## Context
The file I'm trying to open is Skyrim data
Extract The file from .bsa file with BSABrowser

## Steps to Reproduce

 #. 

## Expected Result
Open File

## Possible Fix
I tried to open some files but it didn't work
I think it is unlikely that the data was damaged by the mod modification
## Screenshot
log shot
![スクリーンショット 2021-04-06 182936](https://user-images.githubusercontent.com/43490356/113690152-11d98c80-9706-11eb-9074-4349569f1e0a.png)

Addons
![スクリーンショット 2021-04-06 181225](https://user-images.githubusercontent.com/43490356/113689657-8829bf00-9705-11eb-9924-fc56351025df.png)

## Similar Known Issues
This issue is similar mine. But I cant understand solution in this Thread
https://github.com/niftools/blender_niftools_addon/issues/421

## Additional Information
I'm not very good at English and it's my first time trying a blender, so it could be a misreading of the docs or a very simple problem.
If so, I'm really sorry

**Comment by neomonkeus** [comment] 2021-04-06 09:50
Closing as duplicate of #433, which itself is a duplicate of #405 although I suspect that there is probably an older issue for FO4 support

**Closed by neomonkeus** 2021-04-06 09:50 UTC
Labels: Bug, Duplicate
