### ISSUE TITLE
Can't import. (ValueEror: string too long)

### ISSUE THREAD

**Issue by griseta** [niftools/blender_niftools_addon#544] opened 2022-12-07 23:00 UTC
Hi,

I'm trying to edit the mesh on a Fallout 4 weapon. The two holes in the wooden part that encloses the barrel shouldn't go through to the other side, because the barrel is supposed to be showing through the holes, and I wanted to lengthen the barrel (or otherwise make it look as though there's something going through the wooden part). I installed the addon, tried to import the .nif, and got the error in the linked picture.

[https://i.imgur.com/NhTUVGl.png](url)

Here is the .nif I was trying to edit:

https://drive.google.com/file/d/1Y0KcAf8kov5wlL2ZTULIsmqi32PI8eT_/view?usp=share_link

I am basically technically illiterate, so I will need everything explained to me like I'm five years old. My apologies.

**Comment by Candoran2** [comment] 2022-12-09 17:25
Duplicate of #473 .

**Closed by Candoran2** 2022-12-09 17:25 UTC
Labels: Bug, Duplicate

**Comment by Candoran2** [comment] 2022-12-09 17:26
Fallout 4 import is somewhat likely happen in the future, but it isn't supported right now (see also the issue I linked).
