### ISSUE TITLE
.nif import error

### ISSUE THREAD

**Issue by SirMcSourTowel** [niftools/blender_niftools_addon#540] opened 2022-11-16 18:56 UTC
![image](https://user-images.githubusercontent.com/35937774/202268333-3bc19931-2e8f-4826-b8fa-417fd92a11fe.png)

New error when tying to import a nif file. I'm not entirely sure if this error is because of the version of Blender I'm using or it's something else. I was able to get the add-on working in 2.8 by editing some of it's code.

**Comment by Candoran2** [comment] 2022-11-16 22:05
This is because there is currently no support for Special Edition meshes. Work is underway to support them, but in the meantime you can convert the nif in question to LE format using SSE Nif Optimizer, and import it then.

**Comment by Candoran2** [comment] 2022-11-16 22:07
Duplicate of #474

**Closed by Candoran2** 2022-11-16 22:07 UTC
Labels: Bug
