### ISSUE TITLE
Tool can't import .nif's with BSTriShape block type

### ISSUE THREAD

**Issue by loonymods** [niftools/blender_niftools_addon#433] opened 2021-04-03 14:56 UTC
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [X] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Attempting to import Skyrim SE .nif's throws out an error. The tool doesn't recognize BSTriShape as an attribute or block type, preventing any .nif's from being imported.

### Blender Niftools Addon Version Info
Addon version _should_ be 0.0.5 (released April 2, 2021), but the documentation still says 0.0.4 and Blender reads it as that version.

### Blender Version Info
Blender version is 2.92.

### Platform information
OS version is Windows 10, 64-bit.

## Context
Attempting to import .nif's from Skyrim Special Edition (after the .nif's have been extracted from the original .bsa's) fails. Skyrim SE's .nif's have probably had some of their attributes changed compared to the original Skyrim as part of Bethesda's updating, and now seem to use BSTriShape for the block type. Full error/console output is below.

## Steps to Reproduce
1. Obtain .nif's with BSTriShape block type(s) (might be used in games other than Skyrim SE.
2. Attempt to open them.
3. Fail.

## Expected Result
The tool successfully imports the .nif files.

## Actual Result
The tool fails to import the .nif files and Blender yells at me.

### Console Output
Python: Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1375, in read
    block = getattr(NifFormat, block_type)()
AttributeError: type object 'NifFormat' has no attribute 'BSTriShape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\nif_import.py", line 144, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\file_io\nif.py", line 64, in load_nif
    data.read(nif_stream)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1378, in read
    "Unknown block type '%s'." % block_type)
ValueError: Unknown block type 'BSTriShape'.

location: <unknown location>:-1

**Comment by neomonkeus** [comment] 2021-04-03 16:05
Closing as duplicate of #405

**Closed by neomonkeus** 2021-04-03 16:05 UTC
Labels: Duplicate
